### ISSUE TITLE
FTS config file dead link

### ISSUE THREAD

**Issue by zxcvbnmone** [FreeTAKTeam/FreeTAKServer-User-Docs#1]
FTS config file dead link https://drive.google.com/open?id=1IK1LfPN13EWikHaMyOuDDwIerNGz-Wl 

Public instance
We support a public instance of FTS.
download the configuration here    <-----------------
use the Import manager in ATAK to import the configuration

**Comment by LargoUsagi** [comment]
Yeah this was broken on the source documents as well.  I need to update it with a new functional link, IIRC it was shared in the discord server recently.

**Comment by LargoUsagi** [comment]
@brothercorvo Could you supply a link the current download for this.

**Comment by LargoUsagi** [comment]
This has been resolved.
