### ISSUE TITLE
FTS Install not running first time wizard

### ISSUE THREAD

**Issue by PHoff00** [FreeTAKTeam/FreeTAKServer-User-Docs#22]
I've installed FTS following the instructions at https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Linux/1_Install/

on the Configure and Run step, I enter `sudo python3 -m FreeTAKServer.controllers.services.FTS` as instructed, but I see no wizard.  Instead, all I see is a stream of messages saying that FTS is running and recieving no messages.  I checked and there is no yaml file generated (screenshot below).

![Screenshot 2022-08-04 122340](https://user-images.githubusercontent.com/83970339/182901752-d61e3685-2dc6-4fb1-bde5-f3b5031a9ada.jpg)

**Comment by brothercorvo** [comment]
please check out the troubleshooting
https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Troubleshooting/troubleshooting/
added to the docs
