### ISSUE TITLE
Bad link in Docs

### ISSUE THREAD

**Issue by NR0X** [FreeTAKTeam/FreeTAKServer-User-Docs#23]
https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs/tree/main/docs/docs/Installation/RaspberryPie)/Installation.md makes reference to a link to download the proper install of ubuntu..

"need to start with new install of ubuntu 20.04 server for pi 64 from: https://cdimage.ubuntu.com/releases/20.04.3/release/ubuntu-20.04.3-preinstalled-server-arm64+raspi.img.xz"

This link is broken, and searching on ubuntu for 20.04.3 only leads to V20.04.4 instead.   I don't know if this affects the function of the easy_install.sh script, however I've been unable to login to the UI without errors.  This may be a separate problem, or it may be a difference in versions.

**Comment by brothercorvo** [comment]
fixed. thank you
