### ISSUE TITLE
Container documentation outdated

### ISSUE THREAD

**Issue by qhaas** [FreeTAKTeam/FreeTAKServer-User-Docs#46]
The [Docker Installation Method](https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs/blob/main/docs/docs/Installation/Docker/Quick%20Start%20Guide.md) directs users to a [Dockerhub Registry](https://hub.docker.com/r/freetakteam/freetakserver) whose images haven't been updated in ~2 years and whose source code [has been archived](https://github.com/FreeTAKTeam/FreeTAKServer-Docker): `The former Docker image for FreeTAKServer, this repo is now archived. Please use the FTS rpository to get the current Container.`

**Comment by brothercorvo** [comment]
added
