### ISSUE TITLE
Clarifying what FTS adds to TAK system

### ISSUE THREAD

**Issue by KevinKW87** [FreeTAKTeam/FreeTAKServer-User-Docs#5]
On the FTS Doc Home page, recommend adding something like the following above the "Community" section (some of these may be incorrect based on my understanding):

FreeTAKServer adds the following capabilities to a TAK network:
1. Data Package upload and retrieval
2. Image transfer and storage
3. COT recording in a database
4. ExCheck plugin functionality (only available to users with takmaps.com access)
5. SSL Encryption for using a server without a VPN

Use of some of these features can be found in the ATAK User Manual.

The following features are planned, but not implemented as of Release 1.3:
1. Web Plugin features
2. Federation Service (Connecting two or more FTS instances)
3. Plugin System
4. Data Sync

The roadmap can be found here: https://github.com/FreeTAKTeam/FreeTakServer/issues/25

**Comment by brothercorvo** [comment]
thank you. your suggestion has been included
